### ISSUE TITLE
xmp-clicked-triggered-email deprecated

### ISSUE THREAD

**Issue by westdigitalfr** [XMPieLab/XMPL-SDK#16]
Hello,
[This other page on Github](https://github.com/XMPieLab/XMPL-SDK/wiki/Triggered-Emails) states that this attribute has been deprecated.
Would you like to consider having [this page](https://github.com/XMPieLab/XMPL-SDK/wiki/Triggered-Emails) updated accordingly?
Thanks!
Kind regards,
Bill

**Comment by BatyahRubin** [comment]
Hi,
Thanks for letting us know.
I corrected the documentation.
All the best,
Batyah
