### ISSUE TITLE
Register / update page

### ISSUE THREAD

**Issue by tomdunning** [XMPieLab/XMPL-SDK#2]
Sample site/registerAndUpdate.html

The approach outlined always results in a registration page, regardless of wether a user exists or not. I'm guessing this is because the page is Anonymous?

**Comment by tmgrook** [comment]
Yep, line 10 in the HTML:

``` javascript
    <div ng-controller="XMPAnonymousPage">
```

From the way I understand the ng-controller directive, no matter if you pass an ?rid= or not, it will not track this or personalize it. I'm not 100% sure if this disables _everything_ XMPie-wise.
To personalize it with some ADORS, try switching line 10 to this:

``` javascript
<div ng-controller="XMPPersonalizedPage">
```

Then your ADORs should function.
