### ISSUE TITLE
Add an example in the wiki where xmp is used in another angularJS controller

### ISSUE THREAD

**Issue by TylerButh** [XMPieLab/XMPL-SDK#3]
I don't understand the following:

> For those of you who wish to use the xmp object in AngularJS programming, note that the xmp object is a member of the scope of the base XMPie controller.

What is the base XMPie controller and how do we inject that into our custom (parent) controller?

**Comment by Ohadcy** [comment]
Hello Tyler,

Two possible controllers are available with XMPL:
XMPPersonalizedPage, which implements a personalized webpage. It identifies the recipient based on the page URL or cookies, and fetches ADORs during page load.
XMPAnonymousPage, which implements an anonymous webpage. The page visitor is not an existing recipient. The page will usually contain a registration form to allow the adding more recipients.

Please see example for the parent controller, from the top menu select 
Code-> XMPL-SDK/Sample Site/indexParentController.html
Note that this page defines its own controller in sampleParent.js:
XMPL-SDK/Sample Site/js/sampleParent.js

Regards,
Ohad Cohen
