### ISSUE TITLE
Issues with the sample SPA code and routing

### ISSUE THREAD

**Issue by Pheebee** [XMPieLab/XMPL-SDK#4]
I've been working with the sample code provided for the SPA and routing, and I can honestly say I had to make some changes to the .when() statements ordering to get the recipientID to work. I have a couple of other issues I'm working through with it now. I will precursor my issues with a statement that I am rather new to AngularJS, so some of my confusion is stemming from that.

First:
The site is routing to my main tracked page, but keeping tacking on #/Register on to the URL. No idea why.

Second:
I added custom directives to the site when I had it setup for individual pages, but they no longer work with the SPA code, I suspect because my ng-app has changed from xmp.app to spaApp. I tried switching the directives to use angular.module('spaApp').... but that was not successful.

I also tried adding "var xmpApp = angular.module('spaApp', ['ngRoute']);" to my custom directives file (just to try something), now all I get is an injector error.

*Note: this issue has been edited since my original posting, as originally I couldn't get the recipientID to look up at all.

**Comment by morenoraf** [comment]
Hi,

Please send us your source code, so we can help you with this issue.

Email to:

Rafael.Moreno@xmpie.com

Regards,

Rafael.
