### ISSUE TITLE
Update on Load with parseInt to increment visits

### ISSUE THREAD

**Issue by bigmoof** [XMPieLab/XMPL-SDK#5]
Your e.g. on [https://github.com/XMPieLab/XMPL-SDK/wiki/Updating-Recipient-Data](https://github.com/XMPieLab/XMPL-SDK/wiki/Updating-Recipient-Data), Angular doesn't seems to evaluate parseInt to convert :
```
<xmp-update-on-page-load xmp-ador="xmp.r['Visited']" 
                         xmp-value="{{1 + parseInt(xmp.r['Visited'],10)}}"/>
```

I've found this : 
[http://stackoverflow.com/questions/26293769/how-to-parseint-in-angular-js](http://stackoverflow.com/questions/26293769/how-to-parseint-in-angular-js) 
and 
```
<xmp-update-on-page-load xmp-ador="xmp.r['Visited']" 
                         xmp-value="{{1 + (xmp.r['Visited']-0)}}"/>

```
seems to do the trick?

**Comment by yaron-tomer** [comment]
Thank you.  We will fix it.
