### ISSUE TITLE
1.9.1 broke xmpResourceDriver

### ISSUE THREAD

**Issue by ghost** [XMPieLab/XMPL-SDK#6]
[https://github.com/XMPieLab/XMPL-SDK/wiki/JavaScript-Access#access-the-xmpl-services-in-a-non-xmpl-page](url)

`var res = new xmpResourceDriver({configuration:xmpcfg},true,true);`
returns
`Uncaught TypeError: xmpResourceDriver is not a constructor`

**Comment by Ohadcy** [comment]
Hello Justin,

From version 1.9.1 and above there are 2 new callback functions that can be used:
• angularComponenetsOnReady 
• xmplOnReady 

More information about these functions can be found here:
https://github.com/XMPieLab/XMPL-SDK/wiki/JavaScript-Access

Here is an example for a custom javascript with xmplOnReady callback function, which is being called in a non angular page:
var xmplOnReady = function() {
	var res = new xmpResourceDriver({configuration: xmpcfg}, true, true);
	.
        .
        .
}

Best Regards,
Ohad Cohen
