### ISSUE TITLE
Error loading the data in the getting started

### ISSUE THREAD

**Issue by MasterBroki** [XMPieLab/XMPL-SDK#7]
Hi,

I found a small error on the wiki page on the getting started. The scripts in the index.html should be in the header, not in the body in order for it to work. Here is a code snippet to replace the actual one:
`<!doctype html>
<html lang="en" ng-app="xmp.app">
<head>
    <meta charset="utf-8">
    <title>Sample Recipient Page</title>
    <link href="https://ajax.xmcircle.com/ajax/libs/xmpl/1.9.1/xmp/css/xmp.css" rel="stylesheet" media="screen">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="https://ajax.xmcircle.com/ajax/libs/xmpl/1.9.1/xmp/js/xmp.min.js"></script>
    <script src="./xmpcfg.js"></script>
</head>
<body>
<div ng-controller="XMPPersonalizedPage" xmp-cloak>
    <div>hello {{xmp.r['First Name']}} {{xmp.r['Last Name']}}</div>
    <div><img xmp-image-asset="xmp.r['MainImage']"/></div>
</div>
</body>
</html>`
on:
https://github.com/XMPieLab/XMPL-SDK/wiki/Getting-Started

Let me know if the mystake is on my side or if I bring a good solution or not.

Thanks!

**Comment by Ohadcy** [comment]
Hello,

Thank you for reporting this bug.
I updated the page

Best Regards,
Ohad Cohen
