### ISSUE TITLE
Angular io (angular 2) compatibility

### ISSUE THREAD

**Issue by MasterBroki** [XMPieLab/XMPL-SDK#8]
hi,

I'm a programmer and I'm working with angular 2. I was wondering if there was a module on its way for the new version or if I have to write it myself?

Thank you for your time!

**Comment by Ohadcy** [comment]
Hello, 

As written in the Cheat-Sheet page, XMPL is built on top of AngularJS 1.3.
https://github.com/XMPieLab/XMPL-SDK/wiki/Cheat-Sheet-for-Web

Regards,
Ohad Cohen

**Comment by Dhamu143** [comment]
i want to use this sdk with angular 5. is this possible right now ?

**Comment by Ohadcy** [comment]
Hi,

The XMPL client library still does not support Angular 5.
However, you can build your own client layer (using Angular 5)  by the XMPL REST APIs.

Regards,,
Ohad Cohen

**Comment by MasterBroki** [comment]
Personnaly, I used the javascript library and I created a service, then declaring a variable on top of the file (as you would do with JQuery). Then I created my layer of functions to be able to use it.

It would be cool to start a little project on github that would serve as a plugin for XMPie lab and angular 2+

**Comment by Dhamu143** [comment]
can i have some demo of your GUI work flow of some more idea about it please ? I am badly stuck with this. i really need help. my email id  : dharmeshkashyap143@gmail.com

**Comment by MasterBroki** [comment]
Right now I'm not really using it, I prefered to create an API on our XMPie's server that makes calls to the uproduce soap API. Personnally  I thought it was a bit more easy as the uProduce API allows you to do more stuff. However this requires some backend knowledge. In case you are more a front end developper I'll create a small angular 2 github project using the javascript api in a few days to demonstrate how I do it
I'll keep you posted

**Comment by Dhamu143** [comment]
thanks a lot. i will wait for it. :+1:

**Comment by Ohadcy** [comment]
Hello Dharmesh, I believe this site will be helpful- http://campus.xmpie.com/.
please contact XMPie support for more information.

Hello Charles, I still suggest to use XMPL REST API because the xmp.min.js library use these calls only.

Regards,
Ohad Cohen

**Comment by Dhamu143** [comment]
where is the documentation of rest API of xmpie?

**Comment by Ohadcy** [comment]
Type in your browser
http://YOUR_XMPL_SERVER/XMPieXMPL_REST_API/help
