### ISSUE TITLE
Hidden field not submitting

### ISSUE THREAD

**Issue by ghost** [XMPieLab/XMPL-SDK#9]
When submitting a hidden input field, the value does not get committed to the database. No errors occur in uProduce or the browser, code sample below:

`<input type="hidden" name="answerTotal" id="answerTotal" xmp-write-ador="xmp.r['answerTotal']" value="0">`

**Comment by Ohadcy** [comment]
Hello,

Note that when you place an ADOR reference using xmp-write-ador, then a two-way connection is created. This means that when the page loads, if the ADOR has also a "read" expression, the field is populated with its value. In case the value of retrieved ADOR is empty, you can use a xmp-default-value attribute which will be used to define an initial value to the referred write ADOR. 

In your code:
`<input type="hidden" name="answerTotal" id="answerTotal" xmp-write-ador="xmp.r['answerTotal']" xmp-default-value="0">`

Regards,
Ohad Cohen
